<!-- Header -->
<header id="header">
    <a class="logo" href="./admin.php">高大圖書館 員工中心</a>
    <div class="dropdown">
        <a href="#" class="nav-link">發行書籍</a>
        <div class="dropdown-content">
            <a href="add_book.php">新增發行書籍</a>
            <a href="admin_manage_book.php">管理發行書籍</a>
        </div>
    </div>
    <div class="dropdown">
        <a href="#" class="nav-link">書籍類別</a>
        <div class="dropdown-content">
            <a href="add_book_category.php">新增書籍類別</a>
            <a href="admin_manage_book_categories.php">管理書籍類別</a>
        </div>
    </div>
    <div class="dropdown">
        <a href="#" class="nav-link">書籍作者</a>
        <div class="dropdown-content">
            <a href="add_author.php">新增書籍作者</a>
            <a href="admin_manage_authors.php">管理書籍作者</a>
        </div>
    </div>
    <a href="admin_record_search.php" class="nav-link">租借記錄查詢</a>
    <nav>
        <a href="#menu">Menu</a>
    </nav>
</header>
<!-- Nav -->
<nav id="menu">
    <ul class="links">
        <li><a href="./adminlogout.php">登出</a></li>
    </ul>
</nav>
<script src="../assets/js/jquery.min.js"></script>
<script src="../assets/js/browser.min.js"></script>
<script src="../assets/js/breakpoints.min.js"></script>
<script src="../assets/js/util.js"></script>
<script src="../assets/js/main.js"></script>